# Config YAML file: 
diigo:
  user: ""
  password: ""
  apikey: ""

nc_bookmarks:
  user: ""
  password: ""
  
auth_timestamp:

diigo_dump_path: "../data/diigo_dump.csv"
nc_dump_path: "../data/nc_dump.csv"

diigo_batch_size: 100
nc_batch_size: 100

ollama: 
  model: "gemma2:9b" 
